# ***************************** BEGIN LICENSE BLOCK ***************************
# 
#  The contents of this file are subject to the Mozilla Public License, v. 2.0.
#  If a copy of the MPL was not distributed with this file, You can obtain one
#  at http://mozilla.org/MPL/2.0/.
#  
#  Software distributed under the License is distributed on an "AS IS" basis,
#  WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
#  for the specific language governing rights and limitations under the License.
# 
#  Copyright (C) 2025 Botts Innovative Research. All Rights Reserved.
# 
# ******************************* END LICENSE BLOCK ***************************

FROM ubuntu:24.04

ENV EUID=1000
RUN ln -s /bin/true /usr/bin/sudo

WORKDIR /app

RUN apt-get update && \
    apt upgrade -y && \
    apt-get install -y \
        git \
        curl \
        build-essential \
        cmake \
        zip \
        unzip \
        lsb-release \
        fontconfig \
        python3.12-venv \
        libgtk-3-dev \
        libexpat1-dev \
        libcurl4-openssl-dev \
        pkg-config \
        python3-dev \
        python3-pip

RUN apt-get clean
RUN git clone https://github.com/ArduPilot/ardupilot.git
RUN /app/ardupilot/Tools/environment_install/install-prereqs-ubuntu.sh -y
RUN echo "Taiwan=24.178772,120.649633,0,0" >> /app/ardupilot/Tools/autotest/locations.txt
RUN echo "Taiwan2=24.178772,120.648633,0,0" >> /app/ardupilot/Tools/autotest/locations.txt
RUN echo "Taiwan3=24.178772,120.647633,0,0" >> /app/ardupilot/Tools/autotest/locations.txt
RUN echo "Taiwan added as location to Ardupilot"
RUN mkdir -p "/root/.mavproxy"
RUN touch "/root/.mavproxy/mavinit.scr"
RUN echo "mavinit.scr created"
RUN echo "output add 127.0.0.1:14540" >> "/root/.mavproxy/mavinit.scr"
RUN echo "output add 127.0.0.1:14560" >> "/root/.mavproxy/mavinit.scr"
RUN echo "output add 127.0.0.1:14550" >> "/root/.mavproxy/mavinit.scr"
RUN echo "outputs added to mavinit.scr"


CMD /bin/bash

