# ***************************** BEGIN LICENSE BLOCK ***************************
# 
#  The contents of this file are subject to the Mozilla Public License, v. 2.0.
#  If a copy of the MPL was not distributed with this file, You can obtain one
#  at http://mozilla.org/MPL/2.0/.
#  
#  Software distributed under the License is distributed on an "AS IS" basis,
#  WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
#  for the specific language governing rights and limitations under the License.
# 
#  Copyright (C) 2025 Botts Innovative Research. All Rights Reserved.
# 
# ******************************* END LICENSE BLOCK ***************************

FROM ubuntu:24.04

WORKDIR /app

RUN apt-get update && \
apt upgrade -y && \
apt-get install -y \
    git \
    curl \
    build-essential \
    cmake \
    zip \ 
    unzip \
    python3-pip &&\
apt-get clean && \
git clone https://github.com/mavlink/MAVSDK.git && \
echo "MAVSDK cloned" && \
cd MAVSDK && \
git submodule update --init --recursive && \
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_MAVSDK_SERVER=ON -Bbuild -S. && \
echo "MAVSDK build config" && \
cmake --build build -j8 && \
echo "MAVSDK built" && \
cmake --build build --target install && \
echo "MAVSDK installed" && \
ldconfig && \
echo "ldconfig updated"


CMD exec mavsdk_server 

